### ISSUE TITLE
Git revert action

### ISSUE THREAD

**Issue by jd** [Mergifyio/mergify#276]
It would be nice to have an action to create a revert from a pull request.

**Comment by AbyelT** [comment]
Hello @jd! is this issue still open for contribution?

**Comment by mkurz** [comment]
Any chance?

**Comment by jd** [comment]
Hi @mkurz !

Everything's possible. What'd be your use case?

**Comment by mkurz** [comment]
> Everything's possible. What'd be your use case?

Quickly reverting a pull request.

**Comment by mkurz** [comment]
Like pull requests that got merged accidentally.

**Comment by jd** [comment]
Knowing that GitHub has a revert button, what'd be the difference in your regard?

**Comment by mkurz** [comment]
Wait... wat? GitHub has... a... revert button? omg... yes you are right I just found it :stuck_out_tongue_winking_eye: Sorry for the noise (I usually never want to revert PRs just today and I thought I tell mergify, because we use it a lot and overlooked the button, thanks!)
