### ISSUE TITLE
Mergify actions are triggered by hiding GitHub comment containing a Mergify command

### ISSUE THREAD

**Issue by teor2345** [Mergifyio/mergify#5032]
## Expected Behavior

When I hide a GitHub comment containing a `@mergifyio` command, nothing happens.

## Actual Behavior

When I hide a GitHub comment containing a `@mergifyio` command, Mergify re-executes that command.

## Steps to Reproduce the Problem

  1. Add a `@mergifyio` command to a PR
  2. Wait for it to execute
  3. Hide the comment containing the `@mergifyio` command

This happened on a draft PR, I'm not sure if that matters.

## Specifications

  - Pull Request URL: https://github.com/ZcashFoundation/zebra/pull/4199
      - Unexpected Mergify Actions:
          - https://github.com/ZcashFoundation/zebra/pull/4199#issuecomment-1186628975
          - https://github.com/ZcashFoundation/zebra/pull/4199#issuecomment-1186629214
  - Mergify Config URL: https://github.com/ZcashFoundation/zebra/blob/main/.github/mergify.yml

**Comment by jd** [comment]
Thanks for your report! We've opened a ticket on our side and we'll look into it. I'll keep you posted as we make progress.

**Comment by jd** [comment]
Hi @teor2345 !

I just wanted to inform you we fixed this issue and it should not happen again :)
