### ISSUE TITLE
GitHub thinks that Mergify rebases come from random users

### ISSUE THREAD

**Issue by ulysses4ever** [Mergifyio/mergify#5038]
## Expected Behavior

When Mergify needs to rebase before merging, I expect that newly-created commits are authored by the same person who authored original commits of the PR. Maybe, co-authored by Mergify (not sure about that). And that info is correctly reflected on GitHub.

## Actual Behavior

What I see on GitHub is stunning, e.g.

![2022-09-07_09-09-1662558014](https://user-images.githubusercontent.com/6832600/188893216-48c991d5-a48c-40b3-a883-9cc8f6bf02fc.png)

[source PR is here](https://github.com/haskell/cabal/pull/8383#issuecomment-1217223532)

So, the commits have the right authors, but the message that GitHub produces mentions a random user (who even gets a notification about it iirc).

[Another, smaller example, without an explicit request to rebase is here](https://github.com/haskell/cabal/pull/8449): the author is GH user coot, but in one of the rebase messages we see the GH user andreabedini.

## Steps to Reproduce the Problem

  1. Open a PR.
  2. Wait until the target branch (e.g. `master`) goes ahead.
  3. Explicitly ask Mergify to rebase or satisfy the Mergigy conditions for a merge.
  4. Watch a GH message in the style: `X forced-pushed the Y branch from Z1 to Z1 A hours ago`. Where X is a random user.

## Specifications

  - Pull Request URL: [[1]](https://github.com/haskell/cabal/pull/8383) [[2]](https://github.com/haskell/cabal/pull/8449)
  - [Mergify Config URL](https://github.com/haskell/cabal/blob/a7e765d1a6f7f82a34260995c530d379e0c9ea5c/.github/mergify.yml)

**Comment by jd** [comment]
This is [documented in our FAQ](https://docs.mergify.com/faq/#i-see-a-rebase-and-force-push-done-by-a-member-of-the-repository-but-mergify-actually-did-it), but I admit it's a not visible for rebase. I'll update our docs.

**Comment by ulysses4ever** [comment]
Oh, I'm sorry for missing it in the docs. Thanks a lot for pointing me to the right place!
