### ISSUE TITLE
Backport body says "whatever" instead of errors

### ISSUE THREAD

**Issue by ankush** [Mergifyio/mergify#5040]
reference: https://github.com/frappe/frappe/pull/18108 

<img width="1044" alt="Screenshot 2022-09-13 at 4 40 37 PM" src="https://user-images.githubusercontent.com/9079960/189887662-a9700d15-3e2e-4e6e-a4f4-7f28143ec18e.png">

## Expected Behavior
Check description it has **"whatever"** instead of body or error messages (the usual)

## Actual Behavior
Show error message or nothing if successfuly. Not sure what "whatever" means. 

1. Check this PR https://github.com/frappe/frappe/pull/18108  , we backported using backport label
2. link to config: https://github.com/frappe/frappe/blob/develop/.mergify.yml#L64 

This happened on multiple PRs hence reporting.

**Comment by sileht** [comment]
The patch that introduced the regression has been removed.
