### ISSUE TITLE
Keep getting "random user" notification

### ISSUE THREAD

**Issue by ulysses4ever** [Mergifyio/mergify#5069]
## Actual Behavior

We keep getting

```
⚠️ This pull request got rebased on behalf of a random user of the organization.
This behavior will change on the 1st February 2023, Mergify will pick the author of the pull request instead...
```

## Expected Behavior

It's long past February 1st. Could we stop receiving this message? It's repetitive and became a bit annoying.

## Specifications

  - Pull Request URL: many, but here's one example: https://github.com/haskell/cabal/pull/8720
  - Mergify Config URL: https://github.com/haskell/cabal/blob/ef1e12c9a3d423239644e58385aa25b56bc3bbb3/.github/mergify.yml

**Comment by ulysses4ever** [comment]
I'd like to bump this issue. Since reporting, I thought that a workaround is available, which in my mind was to explicitly set `update_bot_account`. Today I learned that it's a Premium feature. We're an open source project and don't have means to get Premium. Do we have to keep seeing the warning message forever?

**Comment by DanySK** [comment]
This disrupted a lot of workflows for me, too.

**Comment by ulysses4ever** [comment]
Seems resolved now.
