### ISSUE TITLE
Looping <link rel="canonical"> in docs

### ISSUE THREAD

**Issue by nafg** [Mergifyio/mergify#5090]
## Expected Behavior
Canonical URLs should not redirect to non-canonical URLs

## Actual Behavior
They do

## Steps to Reproduce the Problem

  1. Go to https://docs.mergify.com/actions/assign/
  2. It contains `<link rel="canonical" href="https://docs.mergify.com/actions/assign.html">`
  3. Follow that link
  4. It redirects to the previous link:
 
```
HTTP/2 200 

<head>
<meta http-equiv="refresh" content="0; URL=https://docs.mergify.com/actions/assign/">
<link rel="canonical" href="https://docs.mergify.com/actions/assign/">
</head>
```

**Comment by jd** [comment]
We noticed that too, we'll update the docs in a few weeks and that should fix it.

**Comment by DouglasBlackwood** [comment]
Done with new documentation.
