### ISSUE TITLE
Update documentation regarding Merge actions

### ISSUE THREAD

**Issue by SpenderJules** [Mergifyio/mergify#5095]
## Expected Behavior

In this web page: https://docs.mergify.com/actions/merge/
I expect to have the `method` replaced by `merge_method` following this [changelog](https://changelog.mergify.com/changelog/rename-queue-action-method-option-in-mergemethod)

## Actual Behavior
`method` is present in the documentation

## Steps to Reproduce the Problem
Website 

## Specifications

  - Pull Request URL:
  - Mergify Config URL:

**Comment by jd** [comment]
👋  @SpenderJules 

We actually only renamed the `queue` action and not the `merge` action.
In the `queue` action it seemed too confusing to have only `method` as the name.

OTOH it seemed quite clear that `method` in the `merge` action is the merge method.
